# Generated by Django 5.2.17 on 2026-08-12 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('calories', models.PositiveIntegerField(help_text='Calories consumed for this item')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField(help_text='Age in years')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height_cm', models.FloatField(help_text='Height in centimeters')),
                ('weight_kg', models.FloatField(help_text='Weight in kilograms')),
                ('activity_level', models.CharField(choices=[('SED', 'Sedentary (little or no exercise)'), ('LIG', 'Lightly active (1-3 days/week)'), ('MOD', 'Moderately active (3-5 days/week)'), ('ACT', 'Active (6-7 days/week)'), ('VAC', 'Very active (hard exercise/physical job)')], default='SED', max_length=3)),
                ('goal', models.CharField(choices=[('LOSE', 'Lose weight'), ('MAINTAIN', 'Maintain weight'), ('GAIN', 'Gain weight')], default='MAINTAIN', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
